name = "ai-company-core-2-0"
main = "worker.js"
compatibility_date = "2026-10-03"
keep_vars = true
send_metrics = false

[assets]
directory = "."
run_worker_first = ["/api/*"]

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "ai-company-core"
database_id = "54d4fd58-2a54-47af-b904-c76490a8876b"
